name: 'Apify PR toolkit'
description: 'This action automates a couple of processes connected with a management of Github pull requests.'
author: 'Apify'
inputs:
    repo-token:
        required: true
        description: 'Repository Github token'
    org-token:
        required: true
        description: 'Github token with read only access to organization'
runs:
    using: 'node16'
    main: 'dist/index.js'
