name: Apify PR toolkit

on:
  pull_request:
    branches:
      - main
    types: ['labeled', 'unlabeled', 'opened', 'edited']

concurrency: # This is to make sure that it's executed only for the most recent changes of PR.
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  apify-pr-toolkit:
    runs-on: ubuntu-20.04
    steps:
      - name: clone local repository
        uses: actions/checkout@v3

      - name: run pull-request-toolkit action
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          org-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_GITHUB_TOKEN }}
          zenhub-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_ZENHUB_TOKEN }}
